<?php

//TODO: Das in ScienceConstants verschieben

//Umwelt
define ('SC_ID_MORPHING',				1);
define ('SC_ID_SCIENTISTS',				2);
define ('SC_ID_TREES',					3);
define ('SC_ID_STONES',					4);
define ('SC_ID_PLANTS',					5);

define ('SC_ID_CLAM',					6);
define ('SC_ID_BIRCH',					7);
define ('SC_ID_LUMBER',					8);
define ('SC_ID_BARK',					9);
define ('SC_ID_BASALT',					10);
define ('SC_ID_PERMSANDSTONE',			11);
define ('SC_ID_FLINTSTONE',				12);
define ('SC_ID_PYRIT',					13);
define ('SC_ID_HEDGE',					14);
define ('SC_ID_GROUND_NESTER',			15);
define ('SC_ID_BAST',					16);
define ('SC_ID_FLAX',					17);
define ('SC_ID_HEMP',					18);
define ('SC_ID_POLE_WOOD',				19);
define ('SC_ID_FISHING',				20);
define ('SC_ID_ADV_FISHING',			21);
define ('SC_ID_FIRE',					22);
define ('SC_ID_GELATINE',				23);
define ('SC_ID_RESIN',					24);
define ('SC_ID_BIRCH_PITCH',			25);
define ('SC_ID_CONTAINERS',				26);
define ('SC_ID_JOINT',					27);
define ('SC_ID_CLOTHES',				28);
define ('SC_ID_FIBRE',					29);
define ('SC_ID_CORD',					30);
define ('SC_ID_KNOT',					31);
define ('SC_ID_NETS',					32);
define ('SC_ID_SLING',					33);
define ('SC_ID_GLUE',					34);
define ('SC_ID_CATCH_PARTRIDGE',		35);
define ('SC_ID_SHARPEN',				36);
define ('SC_ID_AGRICULTIRE',			37);
define ('SC_ID_ADV_AGRICULTURE',		38);
define ('SC_ID_REED',					39);
define ('SC_ID_SKINNING',				40);
define ('SC_ID_HUNTING',				41);
define ('SC_ID_WEAPON_REVOLUTION',		42);
define ('SC_ID_CHOP_DOWN_TREES',		43);
define ('SC_ID_CREATE_HEDGE',			44);
define ('SC_ID_COOK_MEAT',				45);



//Waffen & Werkzeuge
define ('SC_ID_JAVELIN',				3001);
define ('SC_ID_ADV_JAVELIN',			3002);
define ('SC_ID_HARPOON',				3005);
define ('SC_ID_ADV_HARPOON',			3006);
define ('SC_ID_BOW',					3007);
define ('SC_ID_ADV_BOW',				3008);
define ('SC_ID_BLADE',					3009);
define ('SC_ID_DRILL',					3010);
define ('SC_ID_CLUB',					3011);
define ('SC_ID_ADZE_BEATEN',			3012);
define ('SC_ID_ADZE_SHARPENED',			3013);
define ('SC_ID_AXE_BEATEN',				3014);
define ('SC_ID_AXE_BEATEN_SHARPENED',	3015);
define ('SC_ID_AXE_SHARPENED',			3016);
define ('SC_ID_DIGWOOD',				3017);
define ('SC_ID_WHEEL',					3019);
define ('SC_ID_WALZENBEIL',				3020);
define ('SC_ID_ADV_BOW_SHARPENED',		3021);
define ('SC_ID_ADV_JAVELIN_SHARPENED',	3022);


// Fähigkeiten (Training) und Zusatzwaffen
define ('SC_ID_CAMOUFLAGE',				4001);
define ('SC_ID_MOVE_TREES',				4002);
define ('SC_ID_STICK_PARRY',			4003);
define ('SC_ID_TRAIN_ABDOMINALS',		4004);
define ('SC_ID_PUSH_UP',				4005);
define ('SC_ID_AXE_BLOCK',				4006);
define ('SC_ID_TWO_AXES',				4007);
define ('SC_ID_BOW_AIMING',				4008);
define ('SC_ID_BOW_DIRECT_SHOT',		4009);
define ('SC_ID_BOW_MOVING_TARGETS',		4010);
define ('SC_ID_ATLATL',					4011);
define ('SC_ID_JAVELIN_AIM',			4012);
define ('SC_ID_JAVELIN_DIRECT_THROW',	4013);
define ('SC_ID_JAVELIN_MOVING_TARGETS',	4014);
define ('SC_ID_HERBS',					4015);
define ('SC_ID_ROPE_SKIPPING',			4016);

//Gebäude
define ('SC_ID_STATICS',				1000);
define ('SC_ID_REED_ROOF',				1001);
define ('SC_ID_HUT',					1002);
define ('SC_ID_ADV_HUT',				1003);
define ('SC_ID_LUMBERJACKS_HUT',		1004);
define ('SC_ID_ADV_LUMBERJACKS_HUT',	1005);
define ('SC_ID_ANIMAL_SKIN_TENT',		1006);
define ('SC_ID_FARM',					1007);
define ('SC_ID_ADV_FARM',				1008);
define ('SC_ID_SHED',					1009);

// "Dunkle Macht"
define ('SC_ID_DARK_UNIT',				5001);
?>